[project]
name = "fast-naming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "groq>=0.4.0",
    "azure-ai-inference>=1.0.0b9",
    "google-generativeai>=0.3.0",
    "uvicorn>=0.35.0",
    "google-ai-generativelanguage>=0.3.0",
]
